---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designateagent
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designateagent/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateagent/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designateapis/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designatecentral
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designatecentral/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designatecentral/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designatecentrals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designatecentrals/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designatecentrals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designatemdns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designatemdns/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designatemdns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateproducer
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designateproducer/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateproducer/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateproducers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designateproducers/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateproducers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designates/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateworker
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - designate.openstack.org
  resources:
  - designateworker/finalizers
  verbs:
  - update
- apiGroups:
  - designate.openstack.org
  resources:
  - designateworker/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
